---
- name: Variables from files
  hosts: localServer
  connection: local
  vars_files:
    - course.yaml # vaiables defined in course file here we are calling
  tasks:
   - name: print the person info
     ansible.builtin.debug:
      msg: "Person favourite colour is: {{ FAVCOLOUR }}, name is : {{ NAME }}, CITY: {{ CITY }}"
