---
- name: Functions Demonstration
  hosts: localhost
  connection: local
  vars:
    technologies: "DevOps,Linux,Python" # String
    name: "Sivakumar reddy M"
    gmail: Info@GMAIL.COM
    ipaddress: "19222.168.0.1"
    # dictionary==map
    tags:
      Application: payment
      Environment: dev
    ListTags:
    - key: Application
      value: payment
    - key: Environment
      value: dev
  tasks:
    - name: Use default variable if not defined
      ansible.builtin.debug:
        msg: "My Name is, {{ Name | default('Ramesh') }}"
      # 'Name' is not defined in vars, so it defaults to 'Ramesh'

    - name: Convert string to list using split
      ansible.builtin.debug:
        msg: "Technologies are: {{ technologies | split(',') }}"
      # 'split' turns a string into a list based on a delimiter

    - name: Convert Map to list
      ansible.builtin.debug:
        msg: "Tags are: {{ tags | dict2items }}"

    - name: Transforming lists into dictionaries
      ansible.builtin.debug:
        msg: "tag map: {{ ListTags | items2dict }}"

    - name: read yaml and take it into variable
      ansible.builtin.set_fact:
        student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}" 
        #lookup is a function and file is student.yml, it will read the file and store it in student_yaml

    - name: convert yaml into json
      ansible.builtin.debug:
        msg: "json: {{ student_yaml | to_json  }}"

    - name: Copy the json output to file
      ansible.builtin.copy:
        dest: ./student-data.json
        content: "{{ student_yaml | to_nice_json  }}"  #nice json means human readable
    
    - name: convert uppercase
      ansible.builtin.debug:
        msg: "{{ name | upper }}"

    - name: convert lowercase
      ansible.builtin.debug:
        msg: "{{ gmail | lower }}"

    - name: check IP is valid or not
      ansible.builtin.debug: 
        msg: "{{ ipaddress | ansible.utils.ipv4 }}"

    - name: grep for root
    #ansible.builtin.command: cat /etc/passwd | grep root
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: command_output

    - name: print the command_output
      ansible.builtin.debug:
        msg: "{{ command_output }}"

    - name: redirect the output
      ansible.builtin.command: ls -ltr > /tmp/output.txt
      register: redirect_output
      ignore_errors: true

    - name: print redirect_output
      ansible.builtin.debug:
        msg: "{{ redirect_output }}"

    - name: redirect the output using shell
      ansible.builtin.shell: ls -ltr > /tmp/output.txt
      register: redirect_output

    - name: print redirect_output shell
      ansible.builtin.debug:
        msg: "{{ redirect_output }}"
