---
- name: Functions Demonstration
  hosts: localhost
  connection: local
  vars:
    technologies: "DevOps,Linux,Python" # String
  tasks:
    - name: Use default variable if not defined
      ansible.builtin.debug:
        msg: "My Name is, {{ Name | default('Ramesh') }}"
      # 'Name' is not defined in vars, so it defaults to 'Ramesh'

    - name: Convert string to list using split
      ansible.builtin.debug:
        msg: "Technologies are: {{ technologies | split(',') }}"
      # 'split' turns a string into a list based on a delimiter
